### ISSUE TITLE
Document deploy process for Care in Digital Ocean App platform

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/legacy-docs#48]
Lets document the process of deploying care to DO app platform. 
- [ ] Add the docs to the deploy docs
- [ ] Get it reviewed by @vigneshhari 
- [ ] Publish

**Comment by tellmeY18** [comment]
@dauntlessnomad

**Comment by tellmeY18** [comment]
[#57](https://github.com/ohcnetwork/docs/pull/57
)
Can we close this issue ? 

@bodhish

**Comment by bodhish** [comment]
@tellmeY18 Did you complete the checklist above?
